<?php
/**
 * @file
 * Hooks and theme functions
 */

require_once dirname(__FILE__) . '/includes/utilities.inc';

/**
 * Implements hook_menu().
 */
function islandora_custom_solr_menu() {
  $items = array();
  $items['admin/islandora/tools/custom_solr'] = array(
    'title' => 'Sparql to Solr Replacements',
    'description' => 'Replace sparql queries for some content-models with Solr queries',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_custom_solr_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function islandora_custom_solr_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_custom_solr_newspaper' => array(
      'function' => '__islandora_custom_solr_theme_islandora_newspaper',
      'pattern' => 'islandora_custom_solr_newspaper__',
      'variables' => array('object' => NULL),
      'file' => 'includes/newspaper.inc',
    ),
    'islandora_custom_solr_newspaper_page_select' => array(
      'file' => 'includes/newspaper.inc',
      'variables' => array('object' => NULL),
    ),
    'islandora_custom_solr_book_book' => array(
      'pattern' => 'islandora_custom_solr_book__',
      'template' => 'theme/islandora-custom-solr-book-book',
      'variables' => array('object' => NULL),
      'file' => 'includes/book.inc',
    ),
    'islandora_custom_solr_newspaper_issue' => array(
      'file' => 'includes/newspaper.inc',
      'template' => 'theme/islandora-custom-solr-newspaper-issue',
      'pattern' => 'islandora_custom_solr_newspaper_issue__',
      'variables' => array(
        'object' => NULL,
      ),
    ),
    'islandora_custom_solr_newspaper_page' => array(
      'file' => 'includes/newspaper.inc',
      'template' => 'theme/islandora-custom-solr-newspaper-page',
      'pattern' => 'islandora_custom_solr_newspaper_page__',
      'variables' => array('object' => NULL),
    ),
    'islandora_custom_solr_newspaper_page_select' => array(
      'file' => 'includes/newspaper.inc',
      'variables' => array('object' => NULL),
    ),
    'islandora_custom_solr_newspaper_page_controls' => array(
      'file' => 'includes/newspaper.inc',
      'template' => 'theme/islandora-custom-solr-newspaper-page-controls',
      'variables' => array('object' => NULL),
    ),
    'islandora_custom_solr_newspaper_issue_navigator' => array(
      'file' => 'includes/newspaper.inc',
      'variables' => array(
        'object' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_module_implements_alter().
 */
function islandora_custom_solr_module_implements_alter(&$implementations, $hook) {
  if (
    in_array(strtolower($hook), array(
      'islandora_newspapercmodel_islandora_view_object',
      'islandora_newspaperpagecmodel_islandora_view_object',
      'islandora_newspaperissuecmodel_islandora_view_object',
    )) &&
    variable_get('islandora_custom_solr_replace_newspaper', FALSE)) {
    if (array_key_exists('islandora_newspaper', $implementations)) {
      unset($implementations['islandora_newspaper']);
    }
  }
  elseif (strtolower($hook) == 'islandora_bookcmodel_islandora_view_object' && variable_get('islandora_custom_solr_replace_books', FALSE)) {
    if (array_key_exists('islandora_book', $implementations)) {
      unset($implementations['islandora_book']);
    }
  }
  elseif (strtolower($hook) == 'islandora_compoundcmodel_islandora_view_object' && variable_get('islandora_custom_solr_replace_compound', FALSE)) {
    if (array_key_exists('islandora_compound_object', $implementations)) {
      unset($implementations['islandora_compound_object']);
    }
  }
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_custom_solr_islandora_newspapercmodel_islandora_view_object(AbstractObject $newspaper) {
  if (variable_get('islandora_custom_solr_replace_newspaper', FALSE)) {
    $output = theme('islandora_custom_solr_newspaper', array('object' => $newspaper));
    return array('islandora_custom_solr_newspaper' => $output);
  }
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_custom_solr_islandora_newspaperissuecmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_custom_solr_newspaper_issue', array('object' => $object));
  return array('islandora_custom_solr_newspaper' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_custom_solr_islandora_newspaperpagecmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_custom_solr_newspaper_page', array('object' => $object));
  return array('islandora_custom_solr_newspaper' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_custom_solr_islandora_bookcmodel_islandora_view_object($object) {
  if (variable_get('islandora_custom_solr_replace_books', FALSE)) {
    $output = theme('islandora_custom_solr_book_book', array('object' => $object));
    return array('islandora_custom_solr_book_book' => $output);
  }
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_custom_solr_islandora_compoundCModel_islandora_view_object($object) {
  if (variable_get('islandora_custom_solr_replace_compound', FALSE)) {
    module_load_include('inc', 'islandora_custom_solr', 'includes/compound');
    $children = islandora_custom_solr_compound_object_get_parts($object->id);
    if (!empty($children)) {
      $first_child_id = reset($children);
      if ($first_child_id != $object->id) {
        $first_child = islandora_object_load($first_child_id);
        return islandora_view_object($first_child);
      }
    }
  }
}
