<?php
/**
 * @file
 * Hooks and theme functions
 */

/**
 * Implements hook_menu().
 */
function islandora_custom_solr_menu() {
  $items = array();
  $items['admin/islandora/tools/custom_solr'] = array(
    'title' => 'Sparql to Solr Replacements',
    'description' => 'Replace sparql queries for some content-models with Solr queries',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_custom_solr_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
}

/**
 * Implements hook_theme().
 */
function islandora_custom_solr_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_custom_solr_newspaper' => array(
      'pattern' => 'islandora_newspaper__',
      'variables' => array('object' => NULL),
      'file' => 'includes/newspaper.inc',
    ),
    'islandora_custom_solr_book' => array(
      'pattern' => 'islandora_book__',
      'variables' => array('object' => NULL),
      'file' => 'includes/book.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_custom_solr_islandora_newspapercmodel_islandora_view_object(AbstractObject $newspaper) {
  if (variable_get('islandora_custom_solr_replace_newspaper', FALSE)) {
    $output = theme('islandora_custom_solr_newspaper', array('object' => $newspaper));
    return array('islandora_custom_solr_newspaper' => $output);
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function islandora_custom_solr_module_implements_alter(&$implementations, $hook) {
  if (strtolower($hook) == 'islandora_newspapercmodel_islandora_view_object' &&
    variable_get('islandora_custom_solr_replace_newspaper', FALSE)) {
    if (array_key_exists('islandora_newspaper', $implementations)) {
      unset($implementations['islandora_newspaper']);
    }
  }
  else if (strtolower($hook) == 'islandora_bookcmodel_islandora_view_object' &&
    variable_get('islandora_custom_solr_replace_books', FALSE)) {
    if (array_key_exists('islandora_book', $implementations)) {
      unset($implementations['islandora_book']);
    }
  }
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_custom_solr_islandora_bookcmodel_islandora_view_object($object) {
  if (variable_get('islandora_custom_solr_replace_books', FALSE)) {
    $output = theme('islandora_custom_solr_book', array('object' => $object));
    return array('islandora_custom_solr_book' => $output);
  }
}
