<?php
/**
 * @file
 * Install and uninstall actions.
 */

function islandora_custom_solr_uninstall() {
  $variables = array(
    'islandora_custom_solr_replace_newspaper',
    'islandora_custom_solr_replace_books',
    'islandora_custom_solr_replace_compound',
    'islandora_custom_solr_compound_relationship',
    'islandora_custom_solr_newspaper_relationship',
    'islandora_custom_solr_book_relationship',
    'islandora_custom_solr_newspaper_issued_date',
    'islandora_custom_solr_newspaper_sequence',
    'islandora_custom_solr_newspaper_cache',
  );
  array_walk($variables, 'variable_del');
}
